apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: unix-sort
  description: Sort large streams of JSON objects using the unix sort command.
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
